

name: Java Maven Build & Publish Artifact

on:
  workflow_run:
    workflows: [ "workflowforjava" ]
    types:
      - completed

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
	uses: actions/checkout@v2
	  
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
        
		
      - name: Build with Maven
        run: mvn -B package --file pom.xml


      - name: create Artifact
	run: mkdir staging && cp target/*.jar staging
	working-directory: ${{ github.workspace }}
      - name: upload artifact
	uses: actions/upload-artifact@v2 
	with:
          name: Package
          path: staging
 
